title: PROSTUDIO
email: info@prostudiomoz.com
description: >- # this means to ignore newlines until "baseurl:"
  Video & Fotografias
tagline: Eternizamos Momento
url: "https://prostudiomoz.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  #- jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

collections_dir: collections
collections:
  covers:
  sobre:
  servicos:
  galeria:

# Pagination Settings
pagination:
  enabled: true
  per_page: 80
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
 # extension: htm
 # indexpage: 'default'
  trail: 
    before: 2
    after: 2

sass:
  sass_dir: assets/_sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
